Escape query parameter in searches
SUSE/hackweek pull request #721
Opened 2021-03-09 18:00 UTC by eduardoj

Prevent crashing in search terms including `/`.

Fixes #707.

2021-03-09 18:39 UTC, hennevogel requested changes

2021-03-09 18:39 UTC, hennevogel commented on app/controllers/search_controller.rb
> +    param_q = ThinkingSphinx::Query.escape(params[:q])
```suggestion
    search_query = ThinkingSphinx::Query.escape(params[:q])
```

2021-03-10 08:45 UTC, eduardoj commented on app/controllers/search_controller.rb
> +    param_q = ThinkingSphinx::Query.escape(params[:q])
Changed. Please check it out again.

2021-03-11 16:43 UTC, hennevogel approved these changes

2021-03-11 16:43 UTC, merged